name: CI for SQLite3 Multiple Ciphers
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install dependencies (macOS)
      run: brew install automake
      if: matrix.os == 'macos-latest'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure
      run: |
        autoreconf
        ./configure
    - name: Build
      run: |
        make
    - name: Testing
      run: |
        ./sqlite3shell test1.db3 ".read test/test1.sql"
        ./sqlite3shell test2.db3 ".read test/test2.sql"
        ./sqlite3shell dummy.db3 ".read test/sqlciphertest.sql"

